#!/usr/bin/env bash
# Render the Homebrew formula for a released version from its SHA256SUMS file.
#
#   scripts/homebrew-formula.sh 0.3.0 path/to/SHA256SUMS > Formula/drivesync.rb
#
# SHA256SUMS is the checksum file the release workflow attaches to every GitHub
# release (one "<sha256>  dsync-<os>-<arch>" line per binary). The formula
# installs the prebuilt binary for the current platform, so no Rust toolchain
# is needed on the user's machine.
set -euo pipefail

version=${1:?usage: $0 VERSION SHA256SUMS}
sums=${2:?usage: $0 VERSION SHA256SUMS}
version=${version#v}
base="https://github.com/scaleninja/drivesync/releases/download/v${version}"

sha() {
  local s
  s=$(awk -v f="dsync-$1" '$2 == f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "no checksum for dsync-$1 in $sums" >&2; exit 1; }
  echo "$s"
}

cat <<RUBY
# Generated by scripts/homebrew-formula.sh in scaleninja/drivesync. Do not edit by hand.
class Drivesync < Formula
  desc "Push, pull and diff a local directory against Google Drive"
  homepage "https://scaleninja.com/drivesync/"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${base}/dsync-macos-arm64"
      sha256 "$(sha macos-arm64)"
    end
    on_intel do
      url "${base}/dsync-macos-x86_64"
      sha256 "$(sha macos-x86_64)"
    end
  end

  on_linux do
    on_arm do
      url "${base}/dsync-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "${base}/dsync-linux-x86_64"
      sha256 "$(sha linux-x86_64)"
    end
  end

  def install
    os = OS.mac? ? "macos" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x86_64"
    bin.install "dsync-#{os}-#{arch}" => "dsync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dsync version")
  end
end
RUBY
