#!/usr/bin/env bash
# shellcheck disable=SC2016  # the single-quoted backticks below are markdown, not expansions
# Collect the licence notices of every crate compiled into dsync.
#
#   scripts/third-party-notices.sh > THIRD-PARTY-NOTICES.md          # all release targets
#   scripts/third-party-notices.sh aarch64-apple-darwin > mac.md     # one target
#
# The crates dsync depends on are statically linked, so every binary we publish is a
# distribution of their code. MIT, BSD, ISC, Apache-2.0, Unicode-3.0 and the rest all
# require their notice to travel with that binary; this file is how it does.
#
# The dependency set is taken per target from `cargo metadata --filter-platform`, following
# normal and build dependencies from the root package (dev-dependencies are not shipped), and
# unioned across the targets given. Crates that share a byte-identical licence file are listed
# together under one copy of it, which is what keeps the output readable.
#
# Needs jq and a cargo registry holding the crate sources; `cargo fetch --locked` is enough,
# and a populated registry means the script itself never reaches the network.
set -euo pipefail

case "${1:-}" in
  -h|--help) awk 'NR > 1 && /^#/ { if (!/^# shellcheck/) { sub(/^# ?/, ""); print }; next }
                  NR > 1 { exit }' "$0"; exit 0 ;;
esac

targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
  targets=(
    x86_64-unknown-linux-musl
    aarch64-unknown-linux-musl
    x86_64-apple-darwin
    aarch64-apple-darwin
    x86_64-pc-windows-msvc
  )
fi

root_dir=$(cd "$(dirname "$0")/.." && pwd)
version=$(sed -n 's/^version *= *"\(.*\)"/\1/p' "$root_dir/Cargo.toml" | head -1)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# One "<name>\t<version>\t<licence>\t<crate dir>" line per crate, for every target asked for.
for target in "${targets[@]}"; do
  cargo metadata --format-version 1 --locked --filter-platform "$target" \
      --manifest-path "$root_dir/Cargo.toml" 2>/dev/null |
    jq -r '
      .packages as $pkgs
      | (reduce .resolve.nodes[] as $n ({}; .[$n.id] = $n)) as $nodes
      | .resolve.root as $root
      # Walk the graph from the root, keeping normal and build edges: dev-dependencies
      # build the tests, they are not part of what we ship.
      | def walk($seen; $queue):
          if ($queue | length) == 0 then $seen
          else ($queue[0]) as $id
            | if $seen[$id] then walk($seen; $queue[1:])
              else walk($seen + {($id): true};
                        $queue[1:] + [ $nodes[$id].deps[]
                                       | select([.dep_kinds[].kind] | any(. == null or . == "build"))
                                       | .pkg ])
              end
          end;
        walk({}; [$root]) as $reached
      | $pkgs[]
      | select($reached[.id] and .id != $root)
      | [.name, .version, (.license // .license_file // "see crate"),
         (.manifest_path | sub("/Cargo.toml$"; "")),
         # Never empty: a tab-separated field that is, would be swallowed by `read` below.
         ((.authors // []) | join(", ") | if . == "" then "—" else . end),
         (.repository // "—")]
      | @tsv'
done | sort -u > "$work/crates"

crate_count=$(wc -l < "$work/crates" | tr -d ' ')
[ "$crate_count" -gt 0 ] || { echo "no crates resolved; is the registry populated?" >&2; exit 1; }

# Index every licence file by the checksum of its contents, so identical texts collapse.
: > "$work/index"
: > "$work/missing"
while IFS=$'\t' read -r name ver licence dir authors repo; do
  found=0
  for path in "$dir"/LICENSE* "$dir"/LICENCE* "$dir"/COPYING* "$dir"/NOTICE* "$dir"/UNLICENSE* "$dir"/LICENSES/*; do
    [ -f "$path" ] || continue
    sum=$(shasum -a 256 "$path" | cut -d' ' -f1)
    printf '%s\t%s %s\t%s\n' "$sum" "$name" "$ver" "$path" >> "$work/index"
    found=1
  done
  [ "$found" -eq 1 ] || printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$ver" "$licence" "${authors:-—}" "${repo:-—}" >> "$work/missing"
done < "$work/crates"

printf '# Third-party notices\n\n'
printf 'dsync %s links the Rust crates listed below into every binary it ships. They are not\n' "$version"
printf 'ScaleNinja code; each is used under its own licence, reproduced here in full as those\n'
printf 'licences require. dsync itself is MIT-licensed — see [LICENSE](LICENSE).\n\n'
printf 'Generated by `scripts/third-party-notices.sh` for these targets:\n\n'
printf -- '- `%s`\n' "${targets[@]}"
printf '\nA crate that applies to only some of them is still listed; the set is the union.\n\n'
printf '## Components\n\n'
printf '| Crate | Version | Licence |\n| --- | --- | --- |\n'
cut -f1,2,3 "$work/crates" | sort -u | awk -F'\t' '{ printf "| %s | %s | %s |\n", $1, $2, $3 }'
printf '\n%s crates in total.\n\n' "$crate_count"

printf '## Licence texts\n\n'
n=0
cut -f1 "$work/index" | sort -u | while read -r sum; do
  n=$((n + 1))
  file=$(awk -F'\t' -v s="$sum" '$1 == s { print $3; exit }' "$work/index")
  printf '### %s. %s\n\n' "$n" "$(basename "$file")"
  printf 'Applies to:\n\n'
  awk -F'\t' -v s="$sum" '$1 == s { print "- " $2 }' "$work/index" | sort -u
  printf '\n```\n'
  # A stray fence in a licence file would end the block early; there are none today, and the
  # guard keeps that true if a crate ever adds one.
  sed 's/^```/ ```/' "$file"
  printf '```\n\n'
done

if [ -s "$work/missing" ]; then
  printf '## Crates that publish no licence file\n\n'
  printf 'These declare a licence in their manifest but ship no copy of it in the crate. The\n'
  printf 'declared terms apply; the canonical text is at https://spdx.org/licenses/, and the\n'
  printf 'copyright holder is the crate author named here.\n\n'
  printf '| Crate | Version | Declared licence | Author | Source |\n| --- | --- | --- | --- | --- |\n'
  awk -F'\t' '{ printf "| %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5 }' "$work/missing" | sort -u
  printf '\n'
fi
