// SPDX-License-Identifier: MIT
// Copyright (c) 2026 ScaleNinja
// DriveSync (dsync) — https://github.com/scaleninja/drivesync

//! Minimal Google Drive v3 client: list, folder resolution, upload, download, changes feed.
//!
//! Reads are retried freely. Creates ask Drive for a same-named entry first (a stale index never
//! causes a duplicate) and use ids pre-generated by Drive, so a retried create can never produce a
//! duplicate or adopt someone else's file: if the first attempt went through, Drive answers 409 and
//! the file is simply fetched. Large uploads query their resumable session and continue from the
//! last byte Drive received, across restarts. Updates are refused if the file moved, was renamed,
//! or changed since the plan was made. Every request has a timeout scaled to its body so a stalled
//! connection is retried rather than waited on forever.
use crate::auth::Auth;
use crate::sync::{Entry, Existing};
use anyhow::{bail, Context, Result};
use reqwest::blocking::{Body, Client, RequestBuilder, Response};
use reqwest::header::{CONTENT_LENGTH, CONTENT_RANGE, LOCATION, RANGE};
use reqwest::StatusCode;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::io::{Seek, SeekFrom};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::Duration;

const API: &str = "https://www.googleapis.com/drive/v3/files";
const CHANGES: &str = "https://www.googleapis.com/drive/v3/changes";
const UPLOAD: &str = "https://www.googleapis.com/upload/drive/v3/files";
const FIELDS: &str = "id,name,mimeType,modifiedTime,md5Checksum,size";
pub const FOLDER_MIME: &str = "application/vnd.google-apps.folder";
/// Google rejects multipart uploads above 5 MB; larger files use a resumable session.
const MULTIPART_LIMIT: u64 = 5 * 1024 * 1024;
const MAX_ATTEMPTS: u32 = 6;

#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct File {
    pub id: String,
    pub name: String,
    pub mime_type: String,
    pub modified_time: Option<String>,
    pub md5_checksum: Option<String>,
    /// Bytes, as a decimal string (absent for folders and Google-native docs).
    pub size: Option<String>,
}

impl File {
    pub fn is_folder(&self) -> bool {
        self.mime_type == FOLDER_MIME
    }
    /// Google-native docs/sheets/etc. have no binary content to download.
    pub fn is_native_doc(&self) -> bool {
        !self.is_folder() && self.mime_type.starts_with("application/vnd.google-apps.")
    }
    pub fn to_entry(&self) -> Entry {
        Entry {
            mtime_ms: self
                .modified_time
                .as_deref()
                .and_then(crate::sync::parse_rfc3339_ms)
                .unwrap_or(0),
            size: self.size.as_deref().and_then(|s| s.parse().ok()),
            md5: self.md5_checksum.clone(),
            is_dir: self.is_folder(),
            id: Some(self.id.clone()),
            native_doc: self.is_native_doc(),
            unreadable: false,
        }
    }
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ChangedFile {
    #[serde(flatten)]
    pub file: File,
    #[serde(default)]
    pub parents: Vec<String>,
    #[serde(default)]
    pub trashed: bool,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct Change {
    /// Absent for changes that concern a shared drive rather than a file.
    #[serde(default)]
    pub file_id: Option<String>,
    #[serde(default)]
    pub removed: bool,
    #[serde(default)]
    pub file: Option<ChangedFile>,
}

/// One file to upload: where it goes, what it replaces, and where the bytes come from.
#[derive(Clone, Copy)]
pub struct Upload<'a> {
    pub parent_id: &'a str,
    pub name: &'a str,
    pub existing: Option<&'a Existing>,
    pub local: &'a Path,
    /// Workspace-relative path: the key under which an interrupted session is remembered.
    pub rel: &'a str,
    /// RFC 3339 modification time to record on Drive.
    pub modified_time: &'a str,
}

/// Where resumable-upload session URIs are kept so an interrupted upload continues after a restart.
pub trait SessionStore: Sync {
    fn load(&self, path: &str) -> Option<String>;
    fn save(&self, path: &str, uri: &str);
    fn clear(&self, path: &str);
}

/// Time allowed for a request that carries `bytes` of body: a fixed allowance plus a floor
/// transfer rate of 100 KB/s. A stalled transfer therefore fails and is resumed from the last
/// byte Drive received rather than hanging forever, while slow links are not cut off.
pub fn transfer_timeout(bytes: u64) -> Duration {
    Duration::from_secs(120 + bytes / 100_000)
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChangesResponse {
    next_page_token: Option<String>,
    new_start_page_token: Option<String>,
    changes: Vec<Change>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ListResponse {
    next_page_token: Option<String>,
    files: Vec<File>,
}

/// A non-success response from Drive.
#[derive(Debug)]
pub struct ApiError {
    pub status: StatusCode,
    pub body: String,
    pub retryable: bool,
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Drive API error {}: {}", self.status, self.body.trim())
    }
}

impl std::error::Error for ApiError {}

/// Transient failures worth another attempt: network errors, 429, 5xx, Drive's 403 rate limits.
fn retryable(e: &anyhow::Error) -> bool {
    match e.downcast_ref::<ApiError>() {
        Some(api) => api.retryable,
        None => e.downcast_ref::<reqwest::Error>().is_some(),
    }
}

fn is_status(e: &anyhow::Error, status: StatusCode) -> bool {
    e.downcast_ref::<ApiError>()
        .is_some_and(|a| a.status == status)
}

fn api_error(status: StatusCode, body: String) -> ApiError {
    let rate_limited = status == StatusCode::FORBIDDEN && body.contains("ateLimitExceeded");
    ApiError {
        status,
        retryable: status == StatusCode::TOO_MANY_REQUESTS
            || status.is_server_error()
            || rate_limited,
        body,
    }
}

type Build<'a> = &'a dyn Fn(&Client) -> Result<RequestBuilder>;

enum Session {
    Complete(File),
    Offset(u64),
    Gone,
}

/// Cheap to clone and safe to share between worker threads.
#[derive(Clone)]
pub struct Drive {
    http: Client,
    auth: Arc<Mutex<Auth>>,
    /// Ids pre-generated by Drive, handed out one per create.
    ids: Arc<Mutex<Vec<String>>>,
}

impl Drive {
    pub fn new(http: Client, auth: Auth) -> Self {
        Self {
            http,
            auth: Arc::new(Mutex::new(auth)),
            ids: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// A fresh Drive-generated file id. Fetched 100 at a time, so creates cost no extra request.
    fn next_id(&self) -> Result<String> {
        let mut pool = self.ids.lock().unwrap_or_else(|e| e.into_inner());
        if pool.is_empty() {
            #[derive(Deserialize)]
            struct Ids {
                ids: Vec<String>,
            }
            let got: Ids = self
                .send(&|c| {
                    Ok(c.get(format!("{API}/generateIds"))
                        .query(&[("count", "100"), ("space", "drive")]))
                })?
                .json()?;
            pool.extend(got.ids);
        }
        pool.pop().context("Drive returned no ids")
    }

    /// One attempt with a bearer token (refreshing once on 401). Returns the response whatever its status.
    fn raw(&self, build: Build) -> Result<Response> {
        let token = self.auth().token()?;
        let resp = build(&self.http)?.bearer_auth(&token).send()?;
        if resp.status() != StatusCode::UNAUTHORIZED {
            return Ok(resp);
        }
        self.auth().refresh_if_stale(&token)?;
        let token = self.auth().token()?;
        Ok(build(&self.http)?.bearer_auth(&token).send()?)
    }

    fn auth(&self) -> std::sync::MutexGuard<'_, Auth> {
        self.auth.lock().unwrap_or_else(|e| e.into_inner())
    }

    /// Send and require success. With `retry`, transient failures back off and try again; this is
    /// only safe for idempotent requests.
    fn request(&self, build: Build, retry: bool) -> Result<Response> {
        let attempts = if retry { MAX_ATTEMPTS } else { 1 };
        let mut last: Option<anyhow::Error> = None;
        for attempt in 0..attempts {
            if attempt > 0 {
                backoff(
                    attempt - 1,
                    &last.as_ref().map(ToString::to_string).unwrap_or_default(),
                );
            }
            let resp = match self.raw(build) {
                Ok(r) => r,
                Err(e) if retryable(&e) => {
                    last = Some(e);
                    continue;
                }
                Err(e) => return Err(e),
            };
            let status = resp.status();
            if status.is_success() {
                return Ok(resp);
            }
            let err = api_error(status, resp.text().unwrap_or_default());
            if !err.retryable {
                return Err(err.into());
            }
            last = Some(err.into());
        }
        Err(last.unwrap_or_else(|| anyhow::anyhow!("request failed")))
    }

    fn send(&self, build: Build) -> Result<Response> {
        self.request(build, true)
    }

    fn query(&self, q: String) -> Result<Vec<File>> {
        let mut out = Vec::new();
        let mut page_token: Option<String> = None;
        loop {
            let (q, pt) = (q.clone(), page_token.clone());
            let resp: ListResponse = self
                .send(&move |c| {
                    let mut params = vec![
                        ("q", q.clone()),
                        ("fields", format!("nextPageToken,files({FIELDS})")),
                        ("pageSize", "1000".into()),
                        ("spaces", "drive".into()),
                        ("orderBy", "createdTime".into()), // duplicates resolve the same way every time
                    ];
                    if let Some(pt) = &pt {
                        params.push(("pageToken", pt.clone()));
                    }
                    Ok(c.get(API).query(&params))
                })?
                .json()?;
            out.extend(resp.files);
            match resp.next_page_token {
                Some(t) => page_token = Some(t),
                None => return Ok(out),
            }
        }
    }

    pub fn list_children(&self, parent_id: &str) -> Result<Vec<File>> {
        self.query(format!(
            "'{}' in parents and trashed = false",
            escape(parent_id)
        ))
    }

    pub fn find_child(&self, parent_id: &str, name: &str, folder: bool) -> Result<Option<File>> {
        let kind = if folder { "=" } else { "!=" };
        let files = self.query(format!(
            "'{}' in parents and name = '{}' and mimeType {kind} '{FOLDER_MIME}' and trashed = false",
            escape(parent_id),
            escape(name)
        ))?;
        // Drive's name comparison is not documented as case-sensitive; only an exact match counts.
        Ok(files.into_iter().find(|f| f.name == name))
    }

    /// Metadata of one file (also resolves aliases such as `root`).
    pub fn get_file(&self, id: &str) -> Result<File> {
        let url = format!("{API}/{id}");
        Ok(self
            .send(&move |c| Ok(c.get(&url).query(&[("fields", FIELDS)])))?
            .json()?)
    }

    /// Metadata plus the parent ids of one file.
    fn get_file_with_parents(&self, id: &str) -> Result<(File, Vec<String>)> {
        #[derive(Deserialize)]
        struct WithParents {
            #[serde(flatten)]
            file: File,
            #[serde(default)]
            parents: Vec<String>,
        }
        let url = format!("{API}/{id}");
        let w: WithParents = self
            .send(&move |c| {
                Ok(c.get(&url)
                    .query(&[("fields", format!("{FIELDS},parents"))]))
            })?
            .json()?;
        Ok((w.file, w.parents))
    }

    pub fn file_id(&self, alias: &str) -> Result<String> {
        Ok(self.get_file(alias)?.id)
    }

    /// Verify that the sync root is still a live folder: not deleted, not in the trash, not
    /// replaced by a file. Trashing a folder emits no change records for its children, so this
    /// is the only way to notice before writing into (or reading out of) the trash.
    pub fn check_folder(&self, id: &str) -> Result<()> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase")]
        struct Status {
            mime_type: String,
            #[serde(default)]
            trashed: bool,
        }
        let url = format!("{API}/{id}");
        let s: Status =
            match self.send(&move |c| Ok(c.get(&url).query(&[("fields", "mimeType,trashed")]))) {
                Ok(r) => r.json()?,
                Err(e) if is_status(&e, StatusCode::NOT_FOUND) => {
                    bail!(
                    "the remote folder (id {id}) no longer exists on Drive; run `dsync init` again"
                )
                }
                Err(e) => return Err(e),
            };
        if s.trashed {
            bail!("the remote folder (id {id}) is in the Drive trash; restore it or run `dsync init` again");
        }
        if s.mime_type != FOLDER_MIME {
            bail!("the remote id {id} is no longer a folder; run `dsync init` again");
        }
        Ok(())
    }

    /// Create a folder under a pre-generated id. Retrying after an uncertain response is safe:
    /// if the first attempt went through, Drive answers 409 and the folder is fetched instead.
    pub fn create_folder(&self, parent_id: &str, name: &str) -> Result<File> {
        let id = self.next_id()?;
        let body = serde_json::json!({ "id": id, "name": name, "mimeType": FOLDER_MIME, "parents": [parent_id] });
        self.create_with_id(&id, &|c| {
            Ok(c.post(API).query(&[("fields", FIELDS)]).json(&body))
        })
    }

    /// The folder called `name` under `parent_id`, created if there is none. Drive is asked first,
    /// so a folder that appeared since the index was refreshed is adopted rather than duplicated.
    pub fn find_or_create_folder(&self, parent_id: &str, name: &str) -> Result<File> {
        match self.find_child(parent_id, name, true)? {
            Some(f) => Ok(f),
            None => self.create_folder(parent_id, name),
        }
    }

    /// Run a create request whose metadata carries a pre-generated id, retrying transient failures
    /// and treating "already exists" as success.
    fn create_with_id(&self, id: &str, build: Build) -> Result<File> {
        let mut last = None;
        for attempt in 0..MAX_ATTEMPTS {
            if attempt > 0 {
                backoff(
                    attempt - 1,
                    &last.as_ref().map(ToString::to_string).unwrap_or_default(),
                );
            }
            match self.request(build, false) {
                Ok(resp) => return Ok(resp.json()?),
                Err(e) if is_status(&e, StatusCode::CONFLICT) => return self.get_file(id), // earlier attempt succeeded
                Err(e) if retryable(&e) => last = Some(e),
                Err(e) => return Err(e),
            }
        }
        Err(last.unwrap_or_else(|| anyhow::anyhow!("create failed")))
    }

    /// Resolve `path` (slash-separated, relative to `base_id`) to a folder id, creating folders if asked.
    pub fn resolve_folder(
        &self,
        base_id: &str,
        path: &str,
        create: bool,
    ) -> Result<Option<String>> {
        let mut id = base_id.to_string();
        for part in path.split('/').filter(|p| !p.is_empty()) {
            id = match self.find_child(&id, part, true)? {
                Some(f) => f.id,
                None if create => self.create_folder(&id, part)?.id,
                None => return Ok(None),
            };
        }
        Ok(Some(id))
    }

    /// Upload `local` as `name` under `parent_id`, or replace the content of `existing`.
    ///
    /// Before an update the remote file is re-read and must still be where and what the plan saw.
    /// Before a create Drive is asked whether a same-named file has appeared since the plan; if so
    /// nothing is written. Large uploads use a resumable session whose URI is kept in `sessions`
    /// (keyed by the workspace path) so a run interrupted mid-transfer continues where it stopped.
    pub fn upload(&self, u: &Upload, sessions: &dyn SessionStore) -> Result<File> {
        let Upload {
            parent_id,
            name,
            existing,
            local,
            rel,
            modified_time,
        } = *u;
        let size = std::fs::metadata(local)?.len();
        let mut meta = serde_json::json!({ "name": name, "modifiedTime": modified_time });
        let mut new_id = None;
        match existing {
            Some(ex) => {
                // As close to a precondition as Drive allows. A file that moved out of the sync
                // folder, was renamed, or changed is never written to.
                let (file, parents) = self.get_file_with_parents(&ex.id)?;
                let now = file.to_entry();
                let md5_changed = matches!((&now.md5, &ex.md5), (Some(a), Some(b)) if a != b);
                if md5_changed || (now.mtime_ms - ex.mtime_ms).abs() > 1000 {
                    bail!("remote file changed since the plan was made; re-run to re-plan");
                }
                if !parents.iter().any(|p| p == parent_id) || file.name != name {
                    bail!("remote file was moved or renamed since the plan was made; re-run to re-plan");
                }
            }
            None => {
                if sessions.load(rel).is_none()
                    && self.find_child(parent_id, name, false)?.is_some()
                {
                    bail!("a file with this name appeared on Drive since the plan was made; re-run to re-plan");
                }
                let id = self.next_id()?;
                meta["id"] = serde_json::json!(id);
                meta["parents"] = serde_json::json!([parent_id]);
                new_id = Some(id);
            }
        }
        let url = existing.map_or(UPLOAD.to_string(), |ex| format!("{UPLOAD}/{}", ex.id));
        let is_update = existing.is_some();
        let start = move |c: &Client| {
            if is_update {
                c.patch(&url)
            } else {
                c.post(&url)
            }
        };

        if size > MULTIPART_LIMIT {
            let result =
                self.upload_resumable(&start, &meta, size, local, new_id.as_deref(), rel, sessions);
            if result.is_ok() {
                sessions.clear(rel);
            }
            return result;
        }
        let data = std::fs::read(local)?;
        let boundary = "dsync_boundary_7f3a9c";
        let mut body = Vec::with_capacity(data.len() + 512);
        body.extend_from_slice(format!("--{boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n{meta}\r\n--{boundary}\r\nContent-Type: application/octet-stream\r\n\r\n").as_bytes());
        body.extend_from_slice(&data);
        body.extend_from_slice(format!("\r\n--{boundary}--").as_bytes());
        let timeout = transfer_timeout(body.len() as u64);
        let build = |c: &Client| -> Result<RequestBuilder> {
            Ok(start(c)
                .query(&[("uploadType", "multipart"), ("fields", FIELDS)])
                .header(
                    "Content-Type",
                    format!("multipart/related; boundary={boundary}"),
                )
                .timeout(timeout)
                .body(body.clone()))
        };
        match new_id {
            None => Ok(self.send(&build)?.json()?), // PATCH of content is idempotent
            Some(id) => self.create_with_id(&id, &build),
        }
    }

    /// Resumable upload: open a session (or take over one saved by an earlier run), stream the
    /// file, and after any failure ask the session how many bytes it holds so the transfer
    /// continues from there rather than from zero.
    #[allow(clippy::too_many_arguments)]
    fn upload_resumable(
        &self,
        start: &dyn Fn(&Client) -> RequestBuilder,
        meta: &serde_json::Value,
        size: u64,
        local: &Path,
        new_id: Option<&str>,
        rel: &str,
        sessions: &dyn SessionStore,
    ) -> Result<File> {
        let mut session: Option<String> = sessions.load(rel);
        let mut offset: u64 = 0;
        let mut last = String::new();
        if let Some(s) = &session {
            // Pick up where the earlier run stopped, or discover that it actually finished.
            match self.session_status(s, size)? {
                Session::Complete(f) => return Ok(f),
                Session::Offset(o) => offset = o,
                Session::Gone => session = None,
            }
        }
        for attempt in 0..MAX_ATTEMPTS {
            if attempt > 0 {
                backoff(attempt - 1, &last);
            }
            let sess = match &session {
                Some(s) => s.clone(),
                None => {
                    let init = self.send(&|c| {
                        Ok(start(c)
                            .query(&[("uploadType", "resumable"), ("fields", FIELDS)])
                            .header("X-Upload-Content-Type", "application/octet-stream")
                            .header("X-Upload-Content-Length", size.to_string())
                            .json(meta))
                    });
                    let init = match init {
                        Ok(r) => r,
                        // A create whose earlier session completed after we lost track of it.
                        Err(e) if new_id.is_some() && is_status(&e, StatusCode::CONFLICT) => {
                            return self.get_file(new_id.unwrap())
                        }
                        Err(e) => return Err(e),
                    };
                    let s = init
                        .headers()
                        .get(LOCATION)
                        .and_then(|v| v.to_str().ok())
                        .context("resumable upload: no session URI")?
                        .to_string();
                    offset = 0;
                    sessions.save(rel, &s);
                    session = Some(s.clone());
                    s
                }
            };
            let put = self.raw(&|c| {
                let mut file = std::fs::File::open(local)?;
                file.seek(SeekFrom::Start(offset))?;
                let mut rb = c
                    .put(&sess)
                    .header(CONTENT_LENGTH, size - offset)
                    .timeout(transfer_timeout(size - offset))
                    .body(Body::sized(file, size - offset));
                if offset > 0 {
                    rb = rb.header(CONTENT_RANGE, format!("bytes {offset}-{}/{size}", size - 1));
                }
                Ok(rb)
            });
            match put {
                Ok(resp) if resp.status().is_success() => return Ok(resp.json()?),
                Ok(resp) => {
                    let status = resp.status();
                    let err = api_error(status, resp.text().unwrap_or_default());
                    if !err.retryable
                        && status != StatusCode::NOT_FOUND
                        && status != StatusCode::GONE
                    {
                        return Err(err.into());
                    }
                    last = err.to_string();
                }
                Err(e) if retryable(&e) => last = e.to_string(),
                Err(e) => return Err(e),
            }
            match self.session_status(&sess, size) {
                Ok(Session::Complete(f)) => return Ok(f),
                Ok(Session::Offset(o)) => offset = o,
                Ok(Session::Gone) => {
                    sessions.clear(rel);
                    session = None;
                }
                Err(e) if retryable(&e) => last = format!("{e:#}"),
                Err(e) => return Err(e),
            }
        }
        bail!("resumable upload failed after {MAX_ATTEMPTS} attempts: {last}")
    }

    /// Ask a resumable session what it has received.
    fn session_status(&self, session: &str, size: u64) -> Result<Session> {
        let resp = self.raw(&|c| {
            Ok(c.put(session)
                .header(CONTENT_LENGTH, 0)
                .header(CONTENT_RANGE, format!("bytes */{size}")))
        })?;
        match resp.status() {
            s if s.is_success() => Ok(Session::Complete(resp.json()?)),
            StatusCode::PERMANENT_REDIRECT => {
                let received = resp
                    .headers()
                    .get(RANGE)
                    .and_then(|v| v.to_str().ok())
                    .and_then(parse_range_end)
                    .map_or(0, |end| end + 1);
                Ok(Session::Offset(received.min(size)))
            }
            StatusCode::NOT_FOUND | StatusCode::GONE => Ok(Session::Gone),
            s => Err(api_error(s, resp.text().unwrap_or_default()).into()),
        }
    }

    /// Download into a fresh, exclusively created temp file next to `dest`, verify it against
    /// `expected_md5`, and return the temp path. The caller validates the destination and renames.
    pub fn download_to_temp(
        &self,
        id: &str,
        dest: &Path,
        expected_md5: Option<&str>,
    ) -> Result<PathBuf> {
        let name = dest
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("download");
        let tmp = dest.with_file_name(crate::sync::part_name(name));
        let mut last = None;
        for attempt in 0..3 {
            if attempt > 0 {
                backoff(
                    attempt - 1,
                    &last.as_ref().map(ToString::to_string).unwrap_or_default(),
                );
            }
            match self.try_download(id, &tmp, expected_md5) {
                Ok(()) => return Ok(tmp),
                Err(e) => {
                    let _ = std::fs::remove_file(&tmp);
                    if e.downcast_ref::<ApiError>().is_some_and(|a| !a.retryable) {
                        return Err(e);
                    }
                    last = Some(e);
                }
            }
        }
        Err(last.unwrap_or_else(|| anyhow::anyhow!("download failed")))
    }

    fn try_download(&self, id: &str, tmp: &Path, expected_md5: Option<&str>) -> Result<()> {
        let url = format!("{API}/{id}");
        let mut resp = self.send(&move |c| Ok(c.get(&url).query(&[("alt", "media")])))?;
        let mut writer = HashWriter {
            inner: open_temp_exclusive(tmp)?,
            ctx: md5::Context::new(),
        };
        resp.copy_to(&mut writer).context("reading download body")?;
        writer.inner.sync_all()?;
        let actual = format!("{:x}", writer.ctx.compute());
        if let Some(expected) = expected_md5 {
            if actual != expected {
                bail!("checksum mismatch after download (expected {expected}, got {actual})");
            }
        }
        Ok(())
    }

    /// Token marking "now" in the Changes feed.
    pub fn start_page_token(&self) -> Result<String> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase")]
        struct T {
            start_page_token: String,
        }
        let t: T = self
            .send(&|c| Ok(c.get(format!("{CHANGES}/startPageToken"))))?
            .json()?;
        Ok(t.start_page_token)
    }

    /// All changes in My Drive since `token`, plus the token to use next time.
    pub fn changes(&self, token: &str) -> Result<(Vec<Change>, String)> {
        let mut out = Vec::new();
        let mut page = token.to_string();
        loop {
            let pt = page.clone();
            let resp: ChangesResponse = self
                .send(&move |c| {
                    Ok(c.get(CHANGES).query(&[
                        ("pageToken", pt.as_str()),
                        ("pageSize", "1000"),
                        ("spaces", "drive"),
                        ("includeRemoved", "true"),
                        ("restrictToMyDrive", "true"),
                        ("fields", &format!("nextPageToken,newStartPageToken,changes(fileId,removed,file({FIELDS},parents,trashed))")),
                    ]))
                })?
                .json()?;
            out.extend(resp.changes);
            match (resp.next_page_token, resp.new_start_page_token) {
                (Some(next), _) => page = next,
                (None, Some(new)) => return Ok((out, new)),
                (None, None) => bail!("changes response without newStartPageToken"),
            }
        }
    }

    /// List the whole subtree under `root_id` with one paginated query over My Drive (rclone's
    /// "fast list"): every non-trashed file comes back with its parent id, and the tree is assembled
    /// locally. One request per 1000 files instead of one per folder.
    pub fn list_tree(&self, root_id: &str, depth: i32) -> Result<BTreeMap<String, Entry>> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase")]
        struct Row {
            #[serde(flatten)]
            file: File,
            #[serde(default)]
            parents: Vec<String>,
        }
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase")]
        struct Page {
            next_page_token: Option<String>,
            files: Vec<Row>,
        }
        let mut by_parent: BTreeMap<String, Vec<File>> = BTreeMap::new();
        let mut page_token: Option<String> = None;
        loop {
            let pt = page_token.clone();
            let page: Page = self
                .send(&move |c| {
                    let mut params = vec![
                        ("q", "trashed = false".to_string()),
                        ("fields", format!("nextPageToken,files({FIELDS},parents)")),
                        ("pageSize", "1000".into()),
                        ("spaces", "drive".into()),
                        ("orderBy", "createdTime".into()),
                    ];
                    if let Some(pt) = &pt {
                        params.push(("pageToken", pt.clone()));
                    }
                    Ok(c.get(API).query(&params))
                })?
                .json()?;
            for row in page.files {
                for parent in row.parents {
                    by_parent.entry(parent).or_default().push(row.file.clone());
                }
            }
            match page.next_page_token {
                Some(t) => page_token = Some(t),
                None => break,
            }
        }
        Ok(assemble_tree(&by_parent, root_id, depth))
    }

    /// Recursively list `folder_id` into `out`, keyed by relative path under `prefix`.
    pub fn walk(
        &self,
        folder_id: &str,
        prefix: &str,
        depth: i32,
        out: &mut BTreeMap<String, Entry>,
    ) -> Result<()> {
        if depth == 0 {
            return Ok(());
        }
        for f in self.list_children(folder_id)? {
            if !crate::sync::valid_name(&f.name) {
                crate::progress::eprintln(&format!(
                    "! skip     remote name {:?} cannot be a local path",
                    f.name
                ));
                continue;
            }
            let rel = crate::sync::join_rel(prefix, &f.name);
            if out.contains_key(&rel) {
                continue; // Drive allows duplicate names; keep the first.
            }
            let entry = f.to_entry();
            let is_dir = entry.is_dir;
            out.insert(rel.clone(), entry);
            if is_dir {
                self.walk(&f.id, &rel, depth - 1, out)?;
            }
        }
        Ok(())
    }
}

/// Create the temp file for a download: any stale file or symlink at that path is removed first,
/// then the file is created exclusively (never through a link) with private permissions.
fn open_temp_exclusive(tmp: &Path) -> Result<std::fs::File> {
    match std::fs::remove_file(tmp) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e).with_context(|| format!("removing stale {}", tmp.display())),
    }
    let mut opts = std::fs::OpenOptions::new();
    opts.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.mode(0o600);
    }
    opts.open(tmp)
        .with_context(|| format!("creating {}", tmp.display()))
}

/// Last byte index from a `Range: bytes=0-N` header.
fn parse_range_end(header: &str) -> Option<u64> {
    header
        .trim()
        .strip_prefix("bytes=")?
        .rsplit_once('-')?
        .1
        .parse()
        .ok()
}

/// Writes through to `inner` while computing an MD5 of everything written.
struct HashWriter<W: std::io::Write> {
    inner: W,
    ctx: md5::Context,
}

impl<W: std::io::Write> std::io::Write for HashWriter<W> {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        let n = self.inner.write(buf)?;
        self.ctx.consume(&buf[..n]);
        Ok(n)
    }
    fn flush(&mut self) -> std::io::Result<()> {
        self.inner.flush()
    }
}

/// Build the relative-path map from a parent-id -> children index, breadth-first from `root_id`,
/// honouring `depth`, skipping unmappable names and keeping the first of any duplicate names.
fn assemble_tree(
    by_parent: &BTreeMap<String, Vec<File>>,
    root_id: &str,
    depth: i32,
) -> BTreeMap<String, Entry> {
    let mut out = BTreeMap::new();
    let mut frontier = vec![(root_id.to_string(), String::new(), depth)];
    while let Some((id, prefix, remaining)) = frontier.pop() {
        if remaining == 0 {
            continue;
        }
        for f in by_parent.get(&id).into_iter().flatten() {
            if !crate::sync::valid_name(&f.name) {
                crate::progress::eprintln(&format!(
                    "! skip     remote name {:?} cannot be a local path",
                    f.name
                ));
                continue;
            }
            let rel = crate::sync::join_rel(&prefix, &f.name);
            if out.contains_key(&rel) {
                continue;
            }
            let entry = f.to_entry();
            if entry.is_dir {
                frontier.push((f.id.clone(), rel.clone(), remaining - 1));
            }
            out.insert(rel, entry);
        }
    }
    out
}

/// Sleep 0.5 s, 1 s, 2 s, ... plus jitter before retrying `attempt + 1`.
fn backoff(attempt: u32, why: &str) {
    let mut jitter = [0u8; 2];
    let _ = getrandom::getrandom(&mut jitter);
    let ms = 500 * 2u64.pow(attempt.min(6)) + u64::from(u16::from_le_bytes(jitter)) % 500;
    crate::progress::eprintln(&format!("  retrying in {:.1}s ({why})", ms as f64 / 1000.0));
    std::thread::sleep(Duration::from_millis(ms));
}

/// Escape a value for use inside single quotes in a Drive query.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(id: &str, name: &str, folder: bool) -> File {
        File {
            id: id.into(),
            name: name.into(),
            mime_type: if folder {
                FOLDER_MIME.into()
            } else {
                "text/plain".into()
            },
            modified_time: Some("2026-09-08T00:00:00.000Z".into()),
            md5_checksum: (!folder).then(|| "abc".into()),
            size: (!folder).then(|| "42".into()),
        }
    }

    #[test]
    fn hash_writer_hashes_what_it_writes() {
        use std::io::Write;
        let mut w = HashWriter {
            inner: Vec::new(),
            ctx: md5::Context::new(),
        };
        w.write_all(b"hel").unwrap();
        w.write_all(b"lo").unwrap();
        assert_eq!(w.inner, b"hello");
        assert_eq!(
            format!("{:x}", w.ctx.compute()),
            "5d41402abc4b2a76b9719d911017c592"
        );
    }

    #[test]
    fn query_escaping() {
        assert_eq!(escape("it's"), "it\\'s");
        assert_eq!(escape("back\\slash"), "back\\\\slash");
        assert_eq!(escape("plain name with spaces"), "plain name with spaces");
    }

    #[test]
    fn range_header_parsing() {
        assert_eq!(parse_range_end("bytes=0-42"), Some(42));
        assert_eq!(parse_range_end(" bytes=0-0 "), Some(0));
        assert_eq!(parse_range_end("bytes=0-"), None);
        assert_eq!(parse_range_end("garbage"), None);
    }

    #[test]
    fn api_error_classification() {
        assert!(api_error(StatusCode::TOO_MANY_REQUESTS, String::new()).retryable);
        assert!(api_error(StatusCode::BAD_GATEWAY, String::new()).retryable);
        assert!(api_error(StatusCode::FORBIDDEN, "userRateLimitExceeded".into()).retryable);
        assert!(!api_error(StatusCode::FORBIDDEN, "storageQuotaExceeded".into()).retryable);
        assert!(!api_error(StatusCode::NOT_FOUND, String::new()).retryable);
        let e: anyhow::Error = api_error(StatusCode::NOT_FOUND, "x".into()).into();
        assert!(!retryable(&e));
        assert!(!retryable(&anyhow::anyhow!("plain")));
        let conflict: anyhow::Error = api_error(StatusCode::CONFLICT, "exists".into()).into();
        assert!(is_status(&conflict, StatusCode::CONFLICT) && !retryable(&conflict));
        assert!(!is_status(&e, StatusCode::CONFLICT));
    }

    #[test]
    fn temp_file_is_created_exclusively_and_privately() {
        let dir = std::env::temp_dir().join(format!("dsync_tmp_test_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let tmp = dir.join(crate::sync::part_name("f.txt"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            // A pre-existing symlink at the temp path must not be followed: it is replaced.
            let outside = dir.join("outside.txt");
            std::fs::write(&outside, "keep").unwrap();
            std::os::unix::fs::symlink(&outside, &tmp).unwrap();
            let f = open_temp_exclusive(&tmp).unwrap();
            drop(f);
            assert!(!std::fs::symlink_metadata(&tmp)
                .unwrap()
                .file_type()
                .is_symlink());
            assert_eq!(std::fs::read_to_string(&outside).unwrap(), "keep");
            assert_eq!(
                std::fs::metadata(&tmp).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
        // A stale regular temp file is replaced too.
        std::fs::write(&tmp, "stale").unwrap();
        drop(open_temp_exclusive(&tmp).unwrap());
        assert_eq!(std::fs::metadata(&tmp).unwrap().len(), 0);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn tree_assembly_handles_spaces_depth_duplicates_and_bad_names() {
        let mut by_parent: BTreeMap<String, Vec<File>> = BTreeMap::new();
        by_parent.insert(
            "ROOT".into(),
            vec![
                file("d1", "My Documents", true),
                file("f1", "top level.txt", false),
                file("f1dup", "top level.txt", false),
                file("bad", "with/slash.txt", false),
                file("dot", ".", true),
            ],
        );
        by_parent.insert(
            "d1".into(),
            vec![
                file("d2", "sub folder", true),
                file("f2", "it's 100%_done.md", false),
            ],
        );
        by_parent.insert("d2".into(), vec![file("f3", "deep file.txt", false)]);
        by_parent.insert("dot".into(), vec![file("f4", "unreachable.txt", false)]);

        let all = assemble_tree(&by_parent, "ROOT", -1);
        assert_eq!(
            all.keys().cloned().collect::<Vec<_>>(),
            vec![
                "My Documents",
                "My Documents/it's 100%_done.md",
                "My Documents/sub folder",
                "My Documents/sub folder/deep file.txt",
                "top level.txt"
            ]
        );
        assert_eq!(all["top level.txt"].id.as_deref(), Some("f1")); // first duplicate wins
        assert_eq!(all["top level.txt"].size, Some(42));
        assert!(all["My Documents/sub folder"].is_dir);

        let shallow = assemble_tree(&by_parent, "ROOT", 2);
        assert!(shallow.contains_key("My Documents/sub folder"));
        assert!(!shallow.contains_key("My Documents/sub folder/deep file.txt"));
    }
}
